<a href="https://colab.research.google.com/github/ssosoo/2024_DS60/blob/main/%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98/torch_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [5]:
# 텐서 속성
tensor = torch.rand(1, 2)
print(tensor)
print(tensor.shape) #차원 정보
print(tensor.dtype) #자료형
print(tensor.device)#GPU 가속 여부

tensor([[0.5537, 0.8445]])
torch.Size([1, 2])
torch.float32
cpu


In [6]:
# 차원 변환
tensor = tensor.reshape(2, 1) #전치
print(tensor)
print(tensor.shape)

tensor([[0.5537],
        [0.8445]])
torch.Size([2, 1])


In [7]:
# 자료형 설정
tensor = torch.rand((3,3), dtype=torch.float) #float는 64비트
print(tensor)

tensor([[0.2326, 0.6192, 0.1636],
        [0.0038, 0.9567, 0.3678],
        [0.4729, 0.7583, 0.6396]])


In [9]:
# 장치 설정
# CPU로 설정될 경우 연산에 소요시간이 증가된다.
# M1맥은 CUDA x, mps를 사용한다.


# GPU(MPS) 지원 여부 확인
# device = "mps" if torch.backends.mps.is_available() and torch.backends.mps.is_built() else "cpu"
device = "cuda" if torch.cuda.is_available() else "cpu"

# Tensor 생성
cpu = torch.FloatTensor([1, 2, 3])  # CPU Tensor
gpu = torch.tensor([1, 2, 3], device=device)  # MPS(GPU) Tensor
tensor = torch.rand((1, 1), device=device)

print(device)
print(cpu)
print(gpu)
print(tensor)

cuda
tensor([1., 2., 3.])
tensor([1, 2, 3], device='cuda:0')
tensor([[0.8187]], device='cuda:0')


In [10]:
# 장치 변환
cpu = torch.FloatTensor([1, 2, 3])
gpu = cpu.cuda()
gpu2cpu = gpu.cpu()
cpu2gpu = cpu.to("cuda")
print(cpu)
print(gpu)
print(gpu2cpu)
print(cpu2gpu)

tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')
tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')


GPU 호출 방식

1. device: gpu가 없을 경우 자동으로 cpu 호출
2. .cuda(): gpu가 없을 경우 ERROR

In [14]:
# numpy 배열의 텐서 변환
import numpy as np
ndarray = np.array([1,2,3], dtype=np.uint8)
torch.tensor(ndarray)
torch.Tensor(ndarray)
torch.from_numpy(ndarray)


tensor([1, 2, 3], dtype=torch.uint8)

In [2]:
# 텐서의 numpy 변환
tensor = torch.cuda.FloatTensor([1,2,3])
ndarray = tensor.detach().cpu().numpy()
ndarray
type(ndarray)

<ipython-input-2-c3de2d5b10a8>:2: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:78.)
  tensor = torch.cuda.FloatTensor([1,2,3])


numpy.ndarray